### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by addy-dclxvi** [atrnh/atrnh.github.io#1]
Your colorscheme is too beautiful :heart_eyes:

![urxvt](https://cdn.discordapp.com/attachments/362103290818985985/481646163095846922/Cheese_18.08.22_09.05.50.png)

![inkscape](https://cdn.discordapp.com/attachments/361911930421510144/481632521982050336/Cheese_18.08.22_07.55.55.png)

![thunar](https://cdn.discordapp.com/attachments/361911930421510144/481637681172840461/Cheese_18.08.22_08.34.57.png)

![gimp](https://cdn.discordapp.com/attachments/361911930421510144/481644081944985620/Cheese_18.08.22_08.59.39.png)

I use it everywhere

**Comment by atrnh** [comment]
Thanks! Your setup looks great!

**Comment by atrnh** [comment]
But why did you file this as an issue 🤔

**Comment by addy-dclxvi** [comment]
To surprise you 😆
